export const recipes = [
  {
    id: "erenor-ring-earring",
    profession: "Handicrafts",
    label: "Erenor Ring, Earring",
    defaultQty: 1,
    items: [
      { item: "Diamond", qty: 39 },
      { item: "Ruby", qty: 39 },
      { item: "Sapphire", qty: 39 },
      { item: "Amethyst", qty: 39 },
      { item: "Emerald", qty: 39 },
      { item: "Topaz", qty: 39 },
      { item: "Starlight Archeum Essence", qty: 93 },
      { item: "Gold Ingot", qty: 91 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Starpoint", qty: 10 },
      { item: "Dragon Essence Stabilizer", qty: 50 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  },
  {
    id: "erenor-necklace",
    profession: "Handicrafts",
    label: "Erenor Necklace",
    defaultQty: 1,
    items: [
      { item: "Diamond", qty: 39 },
      { item: "Ruby", qty: 39 },
      { item: "Sapphire", qty: 39 },
      { item: "Amethyst", qty: 39 },
      { item: "Emerald", qty: 39 },
      { item: "Topaz", qty: 39 },
      { item: "Starlight Archeum Essence", qty: 110 },
      { item: "Gold Ingot", qty: 91 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Starpoint", qty: 10 },
      { item: "Dragon Essence Stabilizer", qty: 50 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  },
  {
    id: "erenor-flute-lute",
    profession: "Handicrafts",
    label: "Erenor Flute, Lute",
    defaultQty: 2,
    items: [
      { item: "Rice", qty: 34000 },
      { item: "Peanut", qty: 5100 },
      { item: "Wheat", qty: 5100 },
      { item: "Corn", qty: 34000 },
      { item: "Lumber", qty: 17000 },
      { item: "Anya Ingot", qty: 153 },
      { item: "Sunlight Archeum Essence", qty: 172 },
      { item: "Archeum Ingot", qty: 132 },
      { item: "Flaming Log", qty: 102 },
      { item: "Red Coral", qty: 3400 },
      { item: "Mysterious Garden Powder", qty: 850 },
      { item: "Sunpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Onyx Archeum Essence", qty: 5950 },
      { item: "Dragon Essence Stabilizer", qty: 425 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  },
  {
    id: "erenor-flame-wave-lightning-lunafrost",
    profession: "Alchemy",
    label: "Erenor Flame, Wave, Lightning Lunafrost",
    defaultQty: 1,
    items: [
      { item: "Cactus", qty: 150 },
      { item: "Beechnut", qty: 30 },
      { item: "Diamond", qty: 5 },
      { item: "Ruby", qty: 5 },
      { item: "Sapphire", qty: 5 },
      { item: "Amethyst", qty: 5 },
      { item: "Emerald", qty: 5 },
      { item: "Topaz", qty: 5 },
      { item: "Turmeric", qty: 150 },
      { item: "Moonlight Archeum Dust", qty: 150 },
      { item: "Mysterious Garden Powder", qty: 150 },
      { item: "Book of Auroria", qty: 8 },
      { item: "Sparkling Shell Dust", qty: 30 },
      { item: "Dragon Essence Stabilizer", qty: 59 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "erenor-gale-life-typhoon-lunafrost",
    profession: "Alchemy",
    label: "Erenor Gale, Life, Typhoon Lunafrost",
    defaultQty: 1,
    items: [
      { item: "Red Coral", qty: 150 },
      { item: "Chestnut", qty: 30 },
      { item: "Diamond", qty: 5 },
      { item: "Ruby", qty: 5 },
      { item: "Sapphire", qty: 5 },
      { item: "Amethyst", qty: 5 },
      { item: "Emerald", qty: 5 },
      { item: "Topaz", qty: 5 },
      { item: "Saffron", qty: 150 },
      { item: "Moonlight Archeum Dust", qty: 150 },
      { item: "Mysterious Garden Powder", qty: 150 },
      { item: "Book of Auroria", qty: 8 },
      { item: "Sparkling Shell Dust", qty: 30 },
      { item: "Dragon Essence Stabilizer", qty: 59 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "erenor-earth-ocean-lunafrost",
    profession: "Alchemy",
    label: "Erenor Earth, Ocean Lunafrost",
    defaultQty: 1,
    items: [
      { item: "Lily", qty: 150 },
      { item: "Coconut", qty: 30 },
      { item: "Diamond", qty: 5 },
      { item: "Ruby", qty: 5 },
      { item: "Sapphire", qty: 5 },
      { item: "Amethyst", qty: 5 },
      { item: "Emerald", qty: 5 },
      { item: "Topaz", qty: 5 },
      { item: "Poppy", qty: 150 },
      { item: "Moonlight Archeum Dust", qty: 150 },
      { item: "Mysterious Garden Powder", qty: 150 },
      { item: "Book of Auroria", qty: 8 },
      { item: "Sparkling Shell Dust", qty: 30 },
      { item: "Dragon Essence Stabilizer", qty: 58 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "erenor-bow-scepter-staff",
    profession: "Carpentry",
    label: "Erenor Bow, Scepter, Staff",
    defaultQty: 1,
    items: [
      { item: "Rice", qty: 8500 },
      { item: "Peanut", qty: 1275 },
      { item: "Wheat", qty: 1275 },
      { item: "Corn", qty: 8500 },
      { item: "Lumber", qty: 4250 },
      { item: "Anya Ingot", qty: 39 },
      { item: "Sunlight Archeum Essence", qty: 44 },
      { item: "Archeum Ingot", qty: 32 },
      { item: "Flaming Log", qty: 24 },
      { item: "Red Coral", qty: 850 },
      { item: "Mysterious Garden Powder", qty: 213 },
      { item: "Sunpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Onyx Archeum Essence", qty: 1488 },
      { item: "Dragon Essence Stabilizer", qty: 106 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "erenor-shield",
    profession: "Weaponry",
    label: "Erenor Shield",
    defaultQty: 1,
    items: [
      { item: "Rice", qty: 8500 },
      { item: "Corn", qty: 8500 },
      { item: "Lumber", qty: 4250 },
      { item: "Cultivated Ginseng", qty: 1275 },
      { item: "Bean", qty: 1275 },
      { item: "Anya Ingot", qty: 39 },
      { item: "Sunlight Archeum Essence", qty: 44 },
      { item: "Archeum Ingot", qty: 32 },
      { item: "Flaming Log", qty: 24 },
      { item: "Natural Rubber", qty: 850 },
      { item: "Mysterious Garden Powder", qty: 213 },
      { item: "Sunpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Onyx Archeum Essence", qty: 1488 },
      { item: "Dragon Essence Stabilizer", qty: 106 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "erenor-weapon-set",
    profession: "Weaponry",
    label: "Erenor Dagger, Sword, Greatsword, Katana, Nodachi, Club, Greatclub, Shortspear, Longspear, Axe, Greataxe, Rifle",
    defaultQty: 1,
    items: [
      { item: "Rice", qty: 8500 },
      { item: "Corn", qty: 8500 },
      { item: "Iron Ingot", qty: 4250 },
      { item: "Cultivated Ginseng", qty: 1275 },
      { item: "Bean", qty: 1275 },
      { item: "Anya Ingot", qty: 39 },
      { item: "Sunlight Archeum Essence", qty: 44 },
      { item: "Archeum Ingot", qty: 32 },
      { item: "Flaming Log", qty: 24 },
      { item: "Natural Rubber", qty: 850 },
      { item: "Mysterious Garden Powder", qty: 213 },
      { item: "Sunpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Onyx Archeum Essence", qty: 1488 },
      { item: "Dragon Essence Stabilizer", qty: 106 },
      { item: "Cursed Armor Piece", qty: 1 },
      { item: "Acidic Poison Pouch", qty: 1 }
    ]
  },
  {
    id: "full-plate-set",
    profession: "Metalwork",
    label: "Full Plate Set",
    defaultQty: 1,
    items: [
      { item: "Narcissus", qty: 27900 },
      { item: "Azalea", qty: 27900 },
      { item: "Poppy", qty: 2100 },
      { item: "Bean", qty: 2100 },
      { item: "Turmeric", qty: 1680 },
      { item: "Pepper", qty: 210 },
      { item: "Pearl", qty: 840 },
      { item: "Iron Ingot", qty: 12000 },
      { item: "Anya Ingot", qty: 108 },
      { item: "Moonlight Archeum Essence", qty: 97 },
      { item: "Flaming Log", qty: 72 },
      { item: "Antler Coral", qty: 2940 },
      { item: "Mysterious Garden Powder", qty: 600 },
      { item: "Moonpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Sparkling Shell Dust", qty: 350 },
      { item: "Onyx Archeum Essence", qty: 5155 },
      { item: "Dragon Essence Stabilizer", qty: 455 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  },
  {
    id: "full-leather-set",
    profession: "Leatherwork",
    label: "Full Leather Set",
    defaultQty: 1,
    items: [
      { item: "Blueberry", qty: 2100 },
      { item: "Vanilla", qty: 2100 },
      { item: "Cactus", qty: 1680 },
      { item: "Clover", qty: 27100 },
      { item: "Chestnut", qty: 210 },
      { item: "Rose", qty: 27100 },
      { item: "Poppy", qty: 2100 },
      { item: "Pepper", qty: 210 },
      { item: "Pearl", qty: 840 },
      { item: "Leather", qty: 12000 },
      { item: "Mint", qty: 1680 },
      { item: "Anya Ingot", qty: 108 },
      { item: "Moonlight Archeum Essence", qty: 97 },
      { item: "Flaming Log", qty: 72 },
      { item: "Green Coral", qty: 2940 },
      { item: "Mysterious Garden Powder", qty: 600 },
      { item: "Moonpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Sparkling Shell Dust", qty: 350 },
      { item: "Onyx Archeum Essence", qty: 5155 },
      { item: "Dragon Essence Stabilizer", qty: 455 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  },
  {
    id: "full-cloth-set",
    profession: "Tailoring",
    label: "Full Cloth Set",
    defaultQty: 1,
    items: [
      { item: "Cornflower", qty: 6300 },
      { item: "Lily", qty: 6300 },
      { item: "Cactus", qty: 1400 },
      { item: "Clover", qty: 27100 },
      { item: "Chestnut", qty: 350 },
      { item: "Rose", qty: 27100 },
      { item: "Poppy", qty: 1750 },
      { item: "Pepper", qty: 175 },
      { item: "Pearl", qty: 700 },
      { item: "Fabric", qty: 12000 },
      { item: "Mint", qty: 1400 },
      { item: "Anya Ingot", qty: 108 },
      { item: "Moonlight Archeum Essence", qty: 97 },
      { item: "Flaming Log", qty: 72 },
      { item: "Green Coral", qty: 2940 },
      { item: "Mysterious Garden Powder", qty: 600 },
      { item: "Moonpoint", qty: 10 },
      { item: "Blank Regrade Scroll", qty: 10 },
      { item: "Sparkling Shell Dust", qty: 350 },
      { item: "Onyx Archeum Essence", qty: 5155 },
      { item: "Dragon Essence Stabilizer", qty: 455 },
      { item: "Cursed Armor Piece", qty: 4 },
      { item: "Acidic Poison Pouch", qty: 4 }
    ]
  }
];

function getProfessionOptions() {
  const professions = Array.from(new Set(recipes.map(recipe => recipe.profession)));
  return ["All", ...professions];
}
